spring:
  application:
    name: judge-service
  # 默认 dev 环境
  profiles:
    active: dev
  # todo 上线改地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.126.145:8848
  rabbitmq:
    host: 192.168.126.145
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 192.168.126.145
    port: 6379
    timeout: 5000
    password: 1234
server:
  port: 9300
  servlet:
    context-path: /api/judge